// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCln2d-kmKL6asuz6IZYDNiYvGUrTh8pfA',
    appId: '1:475708650489:web:53ecd11e994b9ec74b8328',
    messagingSenderId: '475708650489',
    projectId: 'fruite-hub',
    authDomain: 'fruite-hub.firebaseapp.com',
    storageBucket: 'fruite-hub.appspot.com',
    measurementId: 'G-GML9TQK0KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-usgasIJatWcKNmeoyv3F2XgxI3mjzQY',
    appId: '1:475708650489:android:b06a9aa62cb1c06d4b8328',
    messagingSenderId: '475708650489',
    projectId: 'fruite-hub',
    storageBucket: 'fruite-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqqqns132TEIC2vm7ELuXCqVYCoSn6Ck',
    appId: '1:475708650489:ios:127dda5865f8268b4b8328',
    messagingSenderId: '475708650489',
    projectId: 'fruite-hub',
    storageBucket: 'fruite-hub.appspot.com',
    iosBundleId: 'com.example.fruitMarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxqqqns132TEIC2vm7ELuXCqVYCoSn6Ck',
    appId: '1:475708650489:ios:127dda5865f8268b4b8328',
    messagingSenderId: '475708650489',
    projectId: 'fruite-hub',
    storageBucket: 'fruite-hub.appspot.com',
    iosBundleId: 'com.example.fruitMarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCln2d-kmKL6asuz6IZYDNiYvGUrTh8pfA',
    appId: '1:475708650489:web:4b1510b4a143af784b8328',
    messagingSenderId: '475708650489',
    projectId: 'fruite-hub',
    authDomain: 'fruite-hub.firebaseapp.com',
    storageBucket: 'fruite-hub.appspot.com',
    measurementId: 'G-CSCGCD3JGE',
  );
}
